services:
  db:
    image: postgres:13-alpine
    container_name: postgresql_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
      
    ports:
      - "5433:5432"
    volumes:
      - D:\postgres_datapart:/var/lib/postgresql/data
    restart: always
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: buysell_app_container
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always
volumes:
  postgres-data: