server:
  error:
    include-message: on_param


spring:
  datasource:
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: buysell
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false


logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
    org.apache.http: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.apache.kafka.clients: INFO




